//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHRealtimeMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_diagram_time_chart
    {
        public string cust_no { get; set; }
        public string cust_type { get; set; }
        public string process_no { get; set; }
        public string start_time { get; set; }
        public string finished_time { get; set; }
        public int cycle_no { get; set; }
        public Nullable<int> prepare_n_date { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string username_id { get; set; }
        public string shipto { get; set; }
    }
}
