//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHRealtimeMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_item_summary
    {
        public Nullable<int> transfer_date { get; set; }
        public Nullable<int> transfer_time { get; set; }
        public string complete_sign { get; set; }
        public string finished_goods_code { get; set; }
        public string record_status { get; set; }
        public string customer_type { get; set; }
        public string customer_code { get; set; }
        public string cust_name { get; set; }
        public string ship_to { get; set; }
        public string delivery_place_name1 { get; set; }
        public string organ_name { get; set; }
        public string line_group { get; set; }
        public string line_no { get; set; }
        public string zone { get; set; }
        public string plant_code { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string mp_code { get; set; }
        public string customer_item { get; set; }
        public string spec_description { get; set; }
        public Nullable<double> fg_weight { get; set; }
        public string box_size { get; set; }
        public string packing_type { get; set; }
        public Nullable<double> pack_qty { get; set; }
        public Nullable<double> box_qty { get; set; }
        public string location_no { get; set; }
        public string compound { get; set; }
        public string kouza { get; set; }
    }
}
