//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHRealtimeMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_picking_order_nics
    {
        public string data_tran_from { get; set; }
        public string data_tran_to { get; set; }
        public string company_code { get; set; }
        public string picking_order_no { get; set; }
        public string picking_order_line_no { get; set; }
        public string customer_order_no { get; set; }
        public string set_item_co_line_no { get; set; }
        public string transaction_no { get; set; }
        public Nullable<int> data_tran_date { get; set; }
        public Nullable<int> data_tran_time { get; set; }
        public string data_code { get; set; }
        public string user_name { get; set; }
        public string customer_code { get; set; }
        public string delivery_place { get; set; }
        public string customer_item { get; set; }
        public string finished_goods_code { get; set; }
        public Nullable<int> co_due_date { get; set; }
        public Nullable<int> co_due_time { get; set; }
        public Nullable<int> issuing_planed_date { get; set; }
        public string customer_po_no { get; set; }
        public string customer_po_line_no { get; set; }
        public string stock_account_no { get; set; }
        public string location_no { get; set; }
        public Nullable<double> picking_order_qty { get; set; }
        public Nullable<double> picking_order_qty_result { get; set; }
        public string issuing_order_type { get; set; }
        public string stock_allocation_sign { get; set; }
        public Nullable<double> sales_unit_price { get; set; }
        public string delivery_place_group { get; set; }
        public Nullable<double> box_qty { get; set; }
        public Nullable<double> pack_qty { get; set; }
        public string code_type { get; set; }
        public string customer_item_nickname { get; set; }
        public Nullable<int> kanban_qty { get; set; }
        public string second_picking_no { get; set; }
        public string kanban_sign { get; set; }
        public Nullable<double> co_qty { get; set; }
        public string plant_code { get; set; }
        public string stock_location { get; set; }
        public string set_item_sign { get; set; }
        public string set_item_child_parts_number { get; set; }
        public Nullable<int> shipped_date { get; set; }
        public Nullable<int> shipped_time { get; set; }
        public string export_ship_to_port { get; set; }
        public string air_boat_sign { get; set; }
        public string ship_to_stock_location { get; set; }
        public string complete_sign { get; set; }
        public string tran_of_control_no { get; set; }
        public string re_inspection_no { get; set; }
        public string re_inspection_line { get; set; }
        public string tran_of_ctrl_to_main_stock_loc { get; set; }
        public string tran_of_control_to_stock_account_no { get; set; }
        public string tran_of_control_to_customer_code { get; set; }
        public string disposal_sign { get; set; }
        public string picking_order_type { get; set; }
        public Nullable<int> hedder_count { get; set; }
        public Nullable<int> line_no_count { get; set; }
        public Nullable<double> issuing_order_qty { get; set; }
        public string tag_no { get; set; }
        public string transfer_ims_no { get; set; }
        public string transfer_finished_goods_code { get; set; }
        public string case_no { get; set; }
    }
}
