//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHRealtimeMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_packing_order_nics
    {
        public string data_tran_from { get; set; }
        public string data_tran_to { get; set; }
        public string company_code { get; set; }
        public string picking_order_no { get; set; }
        public string picking_order_line_no { get; set; }
        public string customer_order_no { get; set; }
        public string set_item_co_line_no { get; set; }
        public string transaction_no { get; set; }
        public Nullable<int> data_tran_date { get; set; }
        public Nullable<int> data_tran_time { get; set; }
        public string data_code { get; set; }
        public string air_boat_sign { get; set; }
        public string customer_code { get; set; }
        public string export_ship_to_port { get; set; }
        public string customer_item { get; set; }
        public string finished_goods_code { get; set; }
        public string plant_code { get; set; }
        public string stock_location { get; set; }
        public string stock_account_no { get; set; }
        public string location_no { get; set; }
        public string customer_po_no { get; set; }
        public string customer_po_line_no { get; set; }
        public Nullable<int> co_due_date { get; set; }
        public Nullable<int> stk_loc_shipment_due_date { get; set; }
        public Nullable<int> etd { get; set; }
        public Nullable<int> eta { get; set; }
        public Nullable<double> co_qty { get; set; }
        public Nullable<double> picking_order_qty { get; set; }
        public Nullable<double> picking_order_qty_result { get; set; }
        public string issuing_order_type { get; set; }
        public string stock_allocation_sign { get; set; }
        public Nullable<double> box_qty { get; set; }
        public Nullable<double> pack_qty { get; set; }
        public string picking_order_type { get; set; }
        public string complete_sign { get; set; }
        public string disposal_sign { get; set; }
        public Nullable<int> header_count { get; set; }
        public Nullable<int> line_no_count { get; set; }
        public Nullable<double> finished_goods_weight { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string customer_memo { get; set; }
        public string parts_no { get; set; }
        public string parts_name { get; set; }
    }
}
