//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHRealtimeMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_realtime_monitoring
    {
        public string tag_no { get; set; }
        public int process_no { get; set; }
        public int status { get; set; }
        public Nullable<int> type { get; set; }
        public string transfer_date { get; set; }
        public string transfer_time { get; set; }
        public Nullable<int> prepare_n_date { get; set; }
        public string finished_time { get; set; }
    }
}
